<a href="https://colab.research.google.com/github/suhasAB/Numpy-Stack/blob/main/GeneratingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.random()

0.28915278995052596

In [7]:
np.random.random((2,3))

array([[0.96941478, 0.06558679, 0.22124928],
       [0.38473125, 0.1605154 , 0.74406433]])

In [8]:
np.random.randn(2,3)

array([[ 1.50266128, -1.51188633,  0.0028106 ],
       [-1.05429952,  1.69630408, -0.44924841]])

In [9]:
R=np.random.randn(10000)

In [10]:
np.mean(R)

0.003502174653571005

In [11]:
np.median(R)

0.0008974467477183714

In [12]:
R.mean()

0.003502174653571005

In [13]:
V=R.var()
V

1.0017277590084024

In [14]:
SD=R.std()
SD

1.000863506682306

In [15]:
np.sqrt(V)

1.000863506682306

In [16]:
np.allclose(np.sqrt(V),SD)

True

In [17]:
R=np.random.randn(10000,3)

In [18]:
R.mean(axis=0)

array([ 0.00200343, -0.0057891 , -0.01086429])

In [19]:
R.mean(axis=1).shape

(10000,)

**Covariance**


In [20]:
np.cov(R).shape

(10000, 10000)

In [21]:
np.cov(R.T)

array([[0.96948796, 0.00616472, 0.0138631 ],
       [0.00616472, 1.00057668, 0.00168434],
       [0.0138631 , 0.00168434, 0.99648176]])

In [22]:
np.cov(R,rowvar=False)

array([[0.96948796, 0.00616472, 0.0138631 ],
       [0.00616472, 1.00057668, 0.00168434],
       [0.0138631 , 0.00168434, 0.99648176]])

**Random Integers**

In [23]:
np.random.randint(0,10,size=(3,3))

array([[4, 9, 1],
       [5, 4, 3],
       [1, 4, 4]])

In [24]:
np.random.choice(10,size=(3,3))

array([[5, 1, 0],
       [0, 1, 6],
       [3, 4, 7]])