<a href="https://colab.research.google.com/github/suhasAB/Numpy-Stack/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
L=[[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [3]:
L[0]

[1, 2]

In [4]:
L[0][1]

2

In [5]:
A= np.array([[1,2],[3,4]])
A[0][1]

2

In [6]:
A[0,1]

2

In [7]:
A[:,0]

array([1, 3])

**Selects everything from 0th column**

In [8]:
A[1,:]

array([3, 4])

**Selects everything from 1st row**

In [9]:
A.T

array([[1, 3],
       [2, 4]])

**A transpose**

In [10]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [11]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

**np converts list into numpy array,the output is also np array**

In [12]:
B= np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [36]:
#A.dot(B.T) 
#this wont work


--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-80d79729e8e6> in <module>()
----> 1 A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [15]:
np.linalg.det(A)

-2.0000000000000004

In [16]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [17]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [18]:
np.trace(A)

5

In [19]:
np.diag(A)

array([1, 4])

In [20]:
np.diag(([1, 4]))

array([[1, 0],
       [0, 4]])

In [21]:
Lam,V=np.linalg.eig(A)

In [22]:
Lam

array([-0.37228132,  5.37228132])

In [23]:
V

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [24]:
V[:,0]* Lam[0] == A @ V[:,0]

array([ True, False])

In [25]:
V[:,0]* Lam[0],A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [26]:
np.allclose(V[:,0]* Lam[0],A @ V[:,0])

True

In [28]:
np.diag(Lam)

array([[-0.37228132,  0.        ],
       [ 0.        ,  5.37228132]])

In [29]:
np.allclose(V @ np.diag(Lam), A @ V)

True

In [31]:
V , np.diag(Lam)

(array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]), array([[-0.37228132,  0.        ],
        [ 0.        ,  5.37228132]]))

In [32]:
A, V

(array([[1, 2],
        [3, 4]]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [38]:
np.linalg.eigh(A)

(array([-0.85410197,  5.85410197]), array([[-0.85065081,  0.52573111],
        [ 0.52573111,  0.85065081]]))

In [ ]:
#np.linalg.eigh(A) is used for complex numbers are in place